name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn
        run: npm i yarn -g
      - name: install modules
        run: yarn
      - name: build production project
        run: yarn build:prod
      - name: linting scss
        run: yarn lint:scss
      - name: unit testing
        run: yarn test:unit
